language: java

env:
  global:
    - CODECOV_TOKEN="a67e36c9-4c07-41fe-a5a7-f6e21104d13a"

before_install:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - ./gradle jacocoTestReport
  - bash <(curl -s https://codecov.io/bash) -t a67e36c9-4c07-41fe-a5a7-f6e21104d13a